"""
Gemini API integration service for the AI Study Assistant.

This module manages communication with the Gemini API and returns
AI-generated responses to the FastAPI application.
"""

import os

from dotenv import load_dotenv
from google import genai

load_dotenv()


GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


if not GEMINI_API_KEY:
    raise ValueError(
        "GEMINI_API_KEY is not configured. "
        "Add the API key to the project's .env file."
    )


client = genai.Client(api_key=GEMINI_API_KEY)


def generate_response(
    user_message: str,
    history: list[dict[str, str]],
) -> str:
    """
    Generate an AI response using the current user message and recent
    conversation history.

    Args:
        user_message (str): The latest message submitted by the user.
        history (list[dict[str, str]]): Previous conversation messages.

    Returns:
        str: The response generated by the Gemini language model.

    Raises:
        RuntimeError: If the Gemini service cannot generate a response.
    """

    recent_history = history[-10:]

    conversation_text = ""

    for message in recent_history:
        role = message["role"]
        content = message["content"]

        if role == "user":
            conversation_text += f"Student: {content}\n"
        else:
            conversation_text += f"Assistant: {content}\n"

    prompt = (
        "You are an AI Study Assistant for university students. "
        "Answer questions clearly, accurately, and concisely.\n\n"
        "STRICT RESPONSE FORMAT:\n"
        "- Return plain text only.\n"
        "- Never use Markdown formatting.\n"
        "- Never use #, ##, ###, **, *, backticks, or triple backticks.\n"
        "- Use the bullet character • for bullet points.\n"
        "- Put every bullet point on a separate line.\n"
        "- Do not use asterisks for bullet points.\n"
        "- Do not use Markdown bold formatting.\n"
        "- Use simple section labels such as 'Key Points:' and 'Example:'.\n\n"
        "RESPONSE STYLE:\n"
        "- Start with a short and direct answer.\n"
        "- For simple questions, provide 3 to 5 concise bullet points when useful.\n"
        "- Include a short practical example when it helps understanding.\n"
        "- Match the response length to the complexity of the question.\n"
        "- Keep each bullet point to one short sentence.\n"
        "- Use no more than 4 bullet points for simple questions.\n"
        "- Do not repeat information unnecessarily.\n"
        "- Do not start with greetings such as 'Welcome' or "
        "'As your study assistant'.\n\n"
        "CONVERSATION CONTEXT:\n"
        "- Use the previous conversation when necessary to understand "
        "follow-up questions.\n"
        "- Understand references such as 'it', 'that', 'this', and "
        "'give me another example'.\n\n"
        "Previous conversation:\n"
        f"{conversation_text}\n"
        f"Student question: {user_message}\n"
        "Assistant:"
    )

    try:
        response = client.interactions.create(
            model="gemini-3.5-flash",
            input=prompt,
        )

        if not response.output_text:
            raise RuntimeError("The AI service returned an empty response.")

        return response.output_text

    except Exception as error:
        raise RuntimeError(
            "Unable to generate a response from the AI service."
        ) from error
