"""
Gemini API integration service for the AI Study Assistant.

This module manages communication with the Google Gemini API,
applies the chatbot's system instruction, incorporates recent
conversation history, and returns AI-generated responses to
the FastAPI application.
"""

import os

from dotenv import load_dotenv
from google import genai


# Load environment variables from the project's local .env file.
load_dotenv()


# Retrieve the Gemini API key without exposing it in source code.
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


if not GEMINI_API_KEY:
    raise ValueError(
        "GEMINI_API_KEY is not configured. "
        "Add the API key to the project's .env file."
    )


# Initialise the Gemini API client.
client = genai.Client(api_key=GEMINI_API_KEY)


# System-level instruction that defines the chatbot's role,
# behaviour, response style, and formatting requirements.
SYSTEM_INSTRUCTION = """
    You are an AI Study Assistant designed to support university students.

    Your role is to:
    - Explain academic concepts clearly and accurately.
    - Use concise and student-friendly language.
    - Provide practical examples when they improve understanding.
    - Use previous conversation context to understand follow-up questions.
    - Understand references such as "it", "that", "this", and
    "give me another example".

    Response requirements:
    - Return plain text only.
    - Do not use Markdown formatting.
    - Do not use #, ##, ###, **, *, backticks, or triple backticks.
    - Use the bullet character • when bullet points are useful.
    - Put each bullet point on a separate line.
    - Keep each bullet point to one short sentence.
    - Use no more than four bullet points for simple questions.
    - Use clear section labels such as "Key Points:" and "Example:".
    - Match the response length to the complexity of the question.
    - Avoid unnecessary repetition.
    - Do not begin responses with unnecessary greetings.
    """


def generate_response(
    user_message: str,
    history: list[dict[str, str]],
) -> str:
    """
    Generate an AI response using the latest user message and recent
    conversation history.

    Args:
        user_message (str): The latest message submitted by the user.
        history (list[dict[str, str]]): Previous user and assistant
            conversation messages.

    Returns:
        str: The response generated by the Gemini language model.

    Raises:
        RuntimeError: If Gemini fails to generate a valid response.
    """

    # Limit conversation context to the ten most recent messages
    # to prevent requests from growing indefinitely.
    recent_history = history[-10:]

    conversation_text = ""

    for message in recent_history:
        role = message["role"]
        content = message["content"]

        if role == "user":
            conversation_text += f"User: {content}\n"
        elif role == "assistant":
            conversation_text += f"Assistant: {content}\n"

    # The system instruction is handled separately by Gemini.
    # This prompt therefore contains only conversation context
    # and the latest user question.
    prompt = (
        "Previous conversation:\n"
        f"{conversation_text}\n"
        f"User: {user_message}\n"
        "Assistant:"
    )

    try:
        response = client.interactions.create(
            model="gemini-3.6-flash",
            system_instruction=SYSTEM_INSTRUCTION,
            input=prompt,
        )

        if not response.output_text:
            raise RuntimeError(
                "The AI service returned an empty response."
            )

        return response.output_text.strip()

    except Exception as error:
        print(
            f"Gemini API error: "
            f"{type(error).__name__}: {error}"
        )

        raise RuntimeError(
            "Unable to generate a response from the AI service."
        ) from error