"""
Gemini API integration service for the AI Study Assistant.

This module manages communication with the Gemini API and provides
AI-generated responses to the FastAPI application.
"""

import os

from dotenv import load_dotenv
from google import genai


# Load environment variables stored in the project's .env file.
load_dotenv()


# Retrieve the Gemini API key without exposing it in the source code.
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


if not GEMINI_API_KEY:
    raise ValueError(
        "GEMINI_API_KEY is not configured. "
        "Add the API key to the project's .env file."
    )


# Initialise the Gemini API client.
client = genai.Client(api_key=GEMINI_API_KEY)


def generate_response(user_message: str) -> str:
    """
    Generate an AI response to a student's question.

    Args:
        user_message (str): The question submitted by the user.

    Returns:
        str: The response generated by the Gemini language model.
    """

    prompt = (
    "You are an AI Study Assistant for university students. "
    "Answer questions clearly, accurately, and concisely. "
    "Use plain text only and do not use Markdown symbols such as "
    "#, ##, ###, **, *, or ```.\n\n"

    "Format simple educational answers using this structure:\n"
    "1. Start with a short definition in one paragraph.\n"
    "2. Add a 'Key Points:' section using the bullet character •.\n"
    "3. Put each bullet point on a separate line.\n"
    "4. Add a short 'Example:' section when an example is useful.\n"
    "5. Keep answers concise unless the student asks for more detail.\n"
    "6. Do not begin with greetings or phrases such as "
    "'Welcome' or 'As your study assistant'.\n\n"

    f"Student question: {user_message}"
    )

    response = client.interactions.create(
        model="gemini-3.5-flash",
        input=prompt,
    )

    return response.output_text